name: Publish Starter
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Starter Repos
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:jamfire/gatsby-starter-jamfire-conference.git
        BRANCH: main
        FOLDER: packages/gatsby-starter-jamfire-conference
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
